"""Turn the silhouette below into internal/render/nelson_data.go.

The only generator here with no source image in assets/art. There is a portrait
of Nelson there, and it is the wrong picture for this: it is the man, head and
shoulders, which at fourteen cells is a smudge. What the menu wants is the
monument, and a monument is a silhouette.

So the shape is drawn below in '#' and '.', and the generator does the shading.
That is the whole reason this is a script rather than a table pasted into the Go
file. Tones placed by hand at this size come out blotchy and every edit means
re-placing them; derived from the shape, the light stays consistent and the art
stays editable.

Run:  python3 assets/monument/generate.py > internal/render/nelson_data.go
"""

W = 14  # columns, and therefore terminal cells

# The monument indexes rampStone from plates_data.go, the same eight greys the
# Abbey plate is drawn in. One stone ramp for every piece of stone in the game:
# a second one defined here would drift against it the first time either was
# retuned, and they would drift in a way nobody would notice until the two were
# on screen together.
RAMP, RAMP_LEN = "rampStone", 8

# HI stops one short of the top of the ramp. The lightest grey is near white,
# which next to the aqua title reads as a highlight on the menu rather than as
# sunlight on stone.
HI, LO, SOFT = 6.0, 1.0, 3

# The statue. What identifies Nelson at seven pixels wide is the bicorne, which
# is why the brim is the widest thing above the capital and there is nothing
# under it but head. The coat steps in by a pixel on his right below the
# epaulettes: that is the empty sleeve, and it is the only asymmetry in the
# figure. Legs are not drawn at all. Two pixels of leg either side of a
# one-pixel gap is speckle, not a man, and the statue wears a coat to the ankle.
STATUE = """
......##......
.....####.....
...########...
......##......
......##......
.....####.....
....######....
....######....
.....#####....
.....#####....
.....#####....
.....#####....
.....####.....
....######....
....######....
.....####.....
"""

# Corinthian capital. It has to be much wider than the figure standing on it or
# the two merge into one tapered stack and the man stops reading as a man.
CAPITAL = """
..##########..
..##########..
...########...
....######....
"""

# One pixel row of shaft, repeated to fill whatever height is left. The column
# is granite and mostly shaft, so this is the part that should stretch.
SHAFT = ".....####....."

PEDESTAL = """
....######....
..##########..
..##########..
.############.
##############
##############
"""


def rows(block):
    out = block.strip().split("\n")
    for i, r in enumerate(out):
        assert len(r) == W, "row %d is %d wide, want %d: %r" % (i, len(r), W, r)
    return out


def shade(art):
    """Silhouette to tone digits, lit from the upper left.

    Each maximal run of lit pixels is graded across its own width, so every form
    reads as round. SOFT stops a narrow run from spanning the whole ramp: a
    two-pixel head given the full range is one white pixel beside one black one,
    which reads as speckle rather than as a head.
    """
    out = []
    for row in art:
        cells = list("." * W)
        x = 0
        while x < W:
            if row[x] != "#":
                x += 1
                continue
            end = x
            while end < W and row[end] == "#":
                end += 1
            n = end - x
            span = max(n - 1, SOFT)
            for i in range(n):
                t = HI - (HI - LO) * i / span
                cells[x + i] = str(max(0, min(RAMP_LEN - 1, int(round(t)))))
            x = end
        out.append("".join(cells))
    return out


def golist(name, art, doc):
    lines = [doc, "var %s = []string{" % name]
    for r in shade(art):
        lines.append('\t"%s",' % r)
    lines.append("}")
    return "\n".join(lines)


def main():
    statue, capital, pedestal = rows(STATUE), rows(CAPITAL), rows(PEDESTAL)
    for part, n in (("statue", statue), ("capital", capital), ("pedestal", pedestal)):
        assert len(n) % 2 == 0, "%s is %d pixel rows; cells are two rows tall" % (part, len(n))
    print('''// Code generated by assets/monument/generate.py. DO NOT EDIT.

package render

// nelsonW is the monument's width in cells. The pixel rows below are one digit
// per pixel: '.' is transparent, '0' to '%d' index nelsonRamp. Two pixel rows to
// a cell, which is what the upper-half block buys.
//
// Transparency is the one way this differs from the plates, which own every
// cell they cover. The monument stands in the menu's left margin with nothing
// behind it, and a bitmap that painted its own background would be a black
// rectangle on the menu rather than a column.
const nelsonW = %d

// nelsonRamp is the stone the monument is drawn in.
var nelsonRamp = &%s
''' % (RAMP_LEN - 1, W, RAMP))

    print(golist("nelsonStatue", statue,
                 "// nelsonStatue is Nelson himself, from the crown of the bicorne to his feet."))
    print()
    print(golist("nelsonCapital", capital,
                 "// nelsonCapital is the Corinthian capital he stands on."))
    print()
    print('''// nelsonShaft is one pixel row of the column, repeated to fill the height that
// is left. The monument is mostly shaft, so this is the part that stretches and
// the reason the art is three pieces rather than one bitmap: one fixed image
// would be squat at 80x24 and stranded at the top of a 40-row terminal.
var nelsonShaft = "%s"''' % shade([SHAFT])[0])
    print()
    print(golist("nelsonPedestal", pedestal,
                 "// nelsonPedestal is the plinth the column rises from."))


if __name__ == "__main__":
    main()
