"""Turn the intro's source images into internal/render/plates_data.go.

Each image ships at three sizes; the intro takes the largest that fits beside or
below its text, so a roomy terminal is not stuck with the size that fits an
80x24 one. Each size is one digit per pixel indexing an eight-tone ramp.

Two things here are not obvious and were both arrived at by looking:

The buildings are inverted. Both prints are dark stone against a bright sky,
which on a dark terminal fills the frame with lit cells and reads as a grey
wall. Inverted, the stone glows against a night sky - which also happens to be
the right hour for the fiction.

The width of every tier is set from the crop's aspect, not chosen. A cell is two
pixel rows tall and character cells are roughly 2:1, so a pixel is roughly
square; getting this wrong is what made the first portrait look stretched.
"""
from PIL import Image, ImageEnhance, ImageOps

# Eight steps per ramp, darkest first. Each holds its hue the whole way up:
# interpolating linearly to white greys out the midtones and the image stops
# matching anything else on screen.
PURPLE = [(8, 6, 14), (30, 24, 46), (56, 45, 82), (84, 68, 122),
          (112, 92, 162), (142, 120, 196), (176, 158, 222), (220, 210, 246)]
STONE = [(8, 8, 10), (28, 29, 33), (52, 54, 60), (80, 83, 90),
         (110, 114, 122), (146, 150, 158), (186, 190, 198), (232, 234, 240)]
NAVY = [(6, 8, 14), (20, 28, 44), (34, 48, 74), (50, 70, 108),
        (70, 96, 144), (98, 128, 178), (140, 168, 208), (206, 224, 246)]

CUTS = (22, 52, 84, 116, 148, 182, 216)

# name -> (file, crop as fractions, palette, invert, cutoff, contrast, gamma,
# row counts). The tone controls are per image because the sources are not alike:
# two aquatints, a pen-and-wash drawing and two oils, and what any of them needs
# was arrived at by rendering it and looking. Nelson needs the most work - the
# painting is dark, and left alone the uniform and the background merge into one
# murk with a pale oval floating in it.
ART = {
    "Abbey": ("westminster-abbey.jpg", (0.10, 0.11, 0.95, 0.76),
              "STONE", True, 1, 1.0, 1.5, (26, 18, 12)),
    "Johnson": ("johnson-reynolds.jpg", (0.18, 0.02, 0.86, 0.52),
                "PURPLE", False, 1, 1.0, 1.0, (26, 18, 12)),
    "Lambeth": ("lambeth-palace.jpg", (0.02, 0.03, 0.99, 0.72),
                "STONE", True, 1, 1.0, 1.5, (18, 12, 8)),
    "Nelson": ("nelson.jpg", (0.16, 0.02, 0.90, 0.58),
               "NAVY", False, 3, 1.25, 0.85, (26, 18, 12)),
}

PALETTES = {"PURPLE": PURPLE, "STONE": STONE, "NAVY": NAVY}

# Above this aspect an image is a band with its text below it rather than a
# panel with its text beside it. Nothing near the boundary; the buildings are
# past 2 and the portraits are near 1.
WIDE = 1.6


def tier(src, box, pal, cols, rows, invert, cutoff, contrast, gamma):
    im = ImageOps.autocontrast(src.crop(box).convert("L"), cutoff=cutoff)
    if invert:
        im = ImageOps.invert(im)
    if contrast != 1.0:
        im = ImageEnhance.Contrast(im).enhance(contrast)
    if gamma != 1.0:
        im = im.point(lambda v: int(255 * ((v / 255) ** gamma)))
    im = im.resize((cols, rows * 2), Image.LANCZOS)
    return ["".join(str(sum(1 for c in CUTS if im.getpixel((x, y)) >= c))
                    for x in range(cols))
            for y in range(rows * 2)]


def main():
    print('''// Code generated by assets/art/generate.py. DO NOT EDIT.

package render

import "github.com/gdamore/tcell/v2"
''')
    for pname, pal in PALETTES.items():
        ramp = ",\n\t".join("tcell.NewHexColor(0x%02X%02X%02X)" % c for c in pal)
        print(f"var ramp{pname.title()} = [8]tcell.Color{{\n\t{ramp},\n}}\n")

    print('''// plateTier is one size of one image. W and H are cells, not pixels: a cell is
// one column wide and two pixel rows tall, so Pixels has 2*H rows.
type plateTier struct {
	W, H   int
	Pixels []string
}

// plateArt is an image at every size it ships at, largest first, with the ramp
// its pixels index. Wide art is drawn as a band with its text below it; the
// rest sits beside its text.
type plateArt struct {
	Ramp  *[8]tcell.Color
	Wide  bool
	Tiers []plateTier
}
''')

    for name, (path, crop, palname, invert, cutoff, contrast, gamma, rows_list) in sorted(ART.items()):
        src = Image.open(path).convert("RGB")
        w, h = src.size
        box = (int(w * crop[0]), int(h * crop[1]), int(w * crop[2]), int(h * crop[3]))
        aspect = (box[2] - box[0]) / (box[3] - box[1])
        wide = "true" if aspect > WIDE else "false"
        print(f"// plate{name}: {path}, crop aspect {aspect:.2f}.")
        print(f"var plate{name} = plateArt{{")
        print(f"\tRamp:  &ramp{palname.title()},")
        print(f"\tWide:  {wide},")
        print("\tTiers: []plateTier{")
        for rows in rows_list:
            cols = int(round(aspect * rows * 2))
            print(f"\t\t{{W: {cols}, H: {rows}, Pixels: []string{{")
            for r in tier(src, box, PALETTES[palname], cols, rows, invert, cutoff, contrast, gamma):
                print(f'\t\t\t"{r}",')
            print("\t\t}},")
        print("\t},\n}\n")


if __name__ == "__main__":
    main()
