// Code generated by assets/monument/generate.py. DO NOT EDIT.

package render

// nelsonW is the monument's width in cells. The pixel rows below are one digit
// per pixel: '.' is transparent, '0' to '7' index nelsonRamp. Two pixel rows to
// a cell, which is what the upper-half block buys.
//
// Transparency is the one way this differs from the plates, which own every
// cell they cover. The monument stands in the menu's left margin with nothing
// behind it, and a bitmap that painted its own background would be a black
// rectangle on the menu rather than a column.
const nelsonW = 14

// nelsonRamp is the stone the monument is drawn in.
var nelsonRamp = &rampStone

// nelsonStatue is Nelson himself, from the crown of the bicorne to his feet.
var nelsonStatue = []string{
	"......64......",
	".....6431.....",
	"...65543221...",
	"......64......",
	"......64......",
	".....6431.....",
	"....654321....",
	"....654321....",
	".....65421....",
	".....65421....",
	".....65421....",
	".....65421....",
	".....6431.....",
	"....654321....",
	"....654321....",
	".....6431.....",
}

// nelsonCapital is the Corinthian capital he stands on.
var nelsonCapital = []string{
	"..6554433221..",
	"..6554433221..",
	"...65543221...",
	"....654321....",
}

// nelsonShaft is one pixel row of the column, repeated to fill the height that
// is left. The monument is mostly shaft, so this is the part that stretches and
// the reason the art is three pieces rather than one bitmap: one fixed image
// would be squat at 80x24 and stranded at the top of a 40-row terminal.
var nelsonShaft = ".....6431....."

// nelsonPedestal is the plinth the column rises from.
var nelsonPedestal = []string{
	"....654321....",
	"..6554433221..",
	"..6554433221..",
	".665544332211.",
	"66554443332211",
	"66554443332211",
}
